[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "xtask"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
clap_mangen = "0.2.28"
owo-colors = "4.2.2"
