onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - msw
  - sharp
allowBuilds:
  '@tailwindcss/oxide': true
  msw: true
  sharp: true
overrides:
  '@types/react': 19.2.17
  '@types/react-dom': 19.2.3
