pub mod backup;
pub mod dsl;
pub mod error;
pub mod manager;
mod modules;
pub mod scripting;
pub mod shuriken;
pub mod templater;
pub mod types;
pub mod util;
pub const VERSION: &str = env!("CARGO_PKG_VERSION");
