[package]
name = "ninja-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
rquickjs = { version = "0.9.0", features = ["futures", "rust-alloc", "loader", "dyn-load", "full", "macro", "bindgen"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
