/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct NinjaManagerOpaque {
  uint8_t _private[0];
} NinjaManagerOpaque;

char *ninja_last_error(void);

void ninja_string_free(char *s);

uint32_t ninja_api_version(void);

struct NinjaManagerOpaque *ninja_manager_new(char **out_err);

void ninja_manager_free(struct NinjaManagerOpaque *mgr);

int32_t ninja_start_shuriken_sync(struct NinjaManagerOpaque *mgr, const char *name, char **out_err);

int32_t ninja_stop_shuriken_sync(struct NinjaManagerOpaque *mgr, const char *name, char **out_err);

char *ninja_list_shurikens_sync(struct NinjaManagerOpaque *mgr, char **out_err);

void ninja_start_shuriken_async(struct NinjaManagerOpaque *mgr,
                                const char *name,
                                void (*cb)(void*, const char*),
                                void *userdata);

void ninja_stop_shuriken_async(struct NinjaManagerOpaque *mgr,
                               const char *name,
                               void (*cb)(void*, const char*),
                               void *userdata);
