/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct NinjaManagerOpaque {
  uint8_t _private[0];
} NinjaManagerOpaque;

char *ninja_last_error(void);

void ninja_string_free(char *s);

uint32_t ninja_api_version(void);

struct NinjaManagerOpaque *ninja_manager_new(char **out_err);

void ninja_manager_free(struct NinjaManagerOpaque *mgr);

int32_t ninja_start_shuriken_sync(struct NinjaManagerOpaque *mgr, const char *name, char **out_err);

int32_t ninja_stop_shuriken_sync(struct NinjaManagerOpaque *mgr, const char *name, char **out_err);

char *ninja_list_shurikens_sync(struct NinjaManagerOpaque *mgr, char **out_err);

void ninja_start_shuriken_async(struct NinjaManagerOpaque *mgr,
                                const char *name,
                                void (*cb)(void*, const char*),
                                void *userdata);

void ninja_stop_shuriken_async(struct NinjaManagerOpaque *mgr,
                               const char *name,
                               void (*cb)(void*, const char*),
                               void *userdata);

int32_t ninja_refresh_sync(struct NinjaManagerOpaque *mgr, char **out_err);

int32_t ninja_configure_sync(struct NinjaManagerOpaque *mgr, const char *name, char **out_err);

int32_t ninja_write_options_toml_sync(struct NinjaManagerOpaque *mgr,
                                      const char *name,
                                      const char *toml_str,
                                      char **out_err);

int32_t ninja_remove_sync(struct NinjaManagerOpaque *mgr, const char *name, char **out_err);

int32_t ninja_install_sync(struct NinjaManagerOpaque *mgr,
                           const char *package_path,
                           char **out_err);

int32_t ninja_forge_sync(struct NinjaManagerOpaque *mgr,
                         const char *meta_json,
                         const char *src_path,
                         const char *output_dir,
                         char **out_err);

char *ninja_get_projects_sync(struct NinjaManagerOpaque *mgr, char **out_err);

char *ninja_get_shuriken_sync(struct NinjaManagerOpaque *mgr, const char *name, char **out_err);

void ninja_refresh_async(struct NinjaManagerOpaque *mgr,
                         void (*cb)(void*, const char*),
                         void *userdata);

void ninja_remove_async(struct NinjaManagerOpaque *mgr,
                        const char *name,
                        void (*cb)(void*, const char*),
                        void *userdata);

void ninja_install_async(struct NinjaManagerOpaque *mgr,
                         const char *package_path,
                         void (*cb)(void*, const char*),
                         void *userdata);

void ninja_forge_async(struct NinjaManagerOpaque *mgr,
                       const char *meta_json,
                       const char *src_path,
                       const char *output_dir,
                       void (*cb)(void*, const char*),
                       void *userdata);
